### ISSUE TITLE
Coordinator: Go Driver

### ISSUE THREAD

**Issue by dyiop** [usnistgov/ATICC#10]
# User Story:

As an ATICC developer, I need to be able to easily all the docker things:
- [ ] Check whether an image exists
- [ ] Run a given image
- [ ] Capture output
- [ ] Check Response Code 
- [ ] Kill in container ~gracefully~

## Goals:

{A clear and concise description of what you want to happen. This should be outcome focused. Include concise description of any alternative solutions or features you've considered. Feel free to include screenshots or examples about the feature request here.}

## Dependencies:

{Describe any previous issues or related work that must be completed to start or complete this issue.}

## Acceptance Criteria

- [ ] 
- [ ] 

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by nikitawootten-nist** [comment]
With the shift towards InSpec profiles, all coordinator/dashboard issues are now out of scope.
