### ISSUE TITLE
Dashboard: Expanding the sendRequest method

### ISSUE THREAD

**Issue by SamuelHoward** [usnistgov/ATICC#18]
# User Story:

As an ATICC developer, I want to be able to send REST requests from the dashboard that are PUT, PATCH, or DELETE requests.

## Goals:

The sendRequest method in the RestService class should be able to send PUT, PATCH, and DELETE requests. Currently, the method only supports GET and POST requests. This functionality can be implemented by expanding the If statement, using a different conditional statement, or using a more general method in the RestTemplate library.

## Dependencies:

NA

## Acceptance Criteria

- [x] Add functionality for sending PUT requests in sendRequest method of RestService class.
- [x] Add functionality for sending PATCH requests in sendRequest method of RestService class.
- [ ] Add functionality for sending DELETE requests in sendRequest method of RestService class.

**Comment by nikitawootten-nist** [comment]
With the shift towards InSpec profiles, all coordinator/dashboard issues are now out of scope.
