### ISSUE TITLE
Dashboard: Edit and Delete

### ISSUE THREAD

**Issue by dyiop** [usnistgov/ATICC#23]
# User Story:

As an ATICC user, I need to be able edit and delete existing instance of tests.

## Goals:

Currently we can only add test to the Dashboard and the only way to delete them is to re-run the whole dashboard. We need to add the ability to both edit and delete existing test to avoid this tedious workaround.
Editing will require some planning because we will need to change the UI a bit to add an "editing" section. Delete should be relatively straight forward.

## Dependencies:

NA

## Acceptance Criteria

- [ ] The UI and functionality to entirely delete existing tests.
- [ ] The UI and functionality to edit existing tests.

**Comment by nikitawootten-nist** [comment]
With the shift towards InSpec profiles, all coordinator/dashboard issues are now out of scope.
