### ISSUE TITLE
Incorporate InSpec parameters into all InSpec profiles

### ISSUE THREAD

**Issue by SamuelHoward** [usnistgov/ATICC#31]
# User Story:

As an ATICC user, I want to be able to easily change values used within the InSpec profiles. This should be doable in one place. An ATICC user should not have to change the actual profiles when changing variable values.

## Goals:

The parameters defined in `/Profile/input_file.yml` should be utilized in all profiles under `/Profile/`

## Acceptance Criteria

- [x] Access Control Profile incorporates relevant InSpec parameters
- [x] Host Containment Profile incorporates relevant InSpec parameters
- [x] Microsegmentation Profile incorporates relevant InSpec parameters
- [x] Network Segmentation Profile incorporates relevant InSpec parameters
- [x] IP Denylisting Profile incorporates relevant InSpec parameters

**Comment by dyiop** [comment]
Everyone did this.
