### ISSUE TITLE
Coordinator: Semantic Error Messages

### ISSUE THREAD

**Issue by dyiop** [usnistgov/ATICC#7]
# User Story:

As an ATICC developer, I need a clear way to view the error that are being made in order to easily diagnose bugs.

## Goals:

As of right now, the go code only return error status codes, and is harder to debug. For cleanliness we should add a universal error logging system so we can write always write errors to it.

## Dependencies:

none

## Acceptance Criteria

- [ ] Create file structure to house go code and log files
- [ ] Implement logging methods in a way that it can be used everywhere.

**Comment by nikitawootten-nist** [comment]
@JedShakarji and I had a discussion on Go error best practices, as well as the features of several logging frameworks. I think we have enough to get started using LogRus. That way we can expand into using some central logging server in the future if required.

**Comment by nikitawootten-nist** [comment]
With the shift towards InSpec profiles, all coordinator/dashboard issues are now out of scope.
